serverAddress: "localhost:5050"
store:
  host: "127.0.0.1"
  port: 9042
  keyspace: "quorumquest"
  table: "services"
  ttl: 3
  consistency: "CONSISTENCY_QUORUM"
  endpoints:
    - "localhost:9042"
logger:
  level: "LOG_LEVELS_INFOLEVEL"
observability:
  serviceName: "quorum-quest"
  serviceVersion: "0.1.0"
  environment: "development"
  otelEndpoint: "localhost:4317"
backend:
  type: "scylladb"