serverAddress: "localhost:5050"
store:
  host: "localhost"
  port: 6379
  password: ""  # Optional
  db: 0
  ttl: 15
  key_prefix: "lock"
logger:
  level: "LOG_LEVELS_INFOLEVEL"
observability:
  serviceName: "quorum-quest"
  serviceVersion: "0.1.0"
  environment: "development"
  otelEndpoint: "localhost:4317"
backend:
  type: "redis"