# /etc/quorum-quest/scylladb-config.yaml
backend: scylladb

# Global application settings
app:
  name: quorum-quest
  env: production
  port: 8080
  graceful_shutdown_timeout: 30s

# ScyllaDB store configuration
store:
  host: 127.0.0.1
  port: 9042
  keyspace: quorum-quest
  table: services
  ttl: 15
  consistency: CONSISTENCY_QUORUM
  endpoints:
    - localhost:9042

# Logger configuration
logger:
  level: info
  format: json

# Observability configuration
observability:
  metrics_address: :9090
  metrics_path: /metrics
  tracing_endpoint: http://tempo:14268/api/traces
  service_name: quorum-quest